language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 -  dotnet test src/Espn.Fantasy.Football.Tests.Integration.NetCore20/Espn.Fantasy.Football.Tests.Integration.NetCore20.csproj