language: csharp
mono: latest
dotnet: 2.0.0

addons:
  sonarcloud:
    organization: "scottenriquez-github"

before_install:
- bash ./tools/travis-ci-install-sonar.sh

install:
- dotnet restore src

script:
 - bash ./tools/travis-ci-build.sh