language: csharp
mono: none
dotnet: 2.0.0

addons:
  sonarcloud:
    organization: "scottenriquez-github"

install:
- dotnet restore src

script:
 - dotnet build src
 - dotnet test src/Espn.Fantasy.Football.Tests.Unit/Espn.Fantasy.Football.Tests.Unit.csproj
 - dotnet test src/Espn.Fantasy.Football.Tests.Integration/Espn.Fantasy.Football.Tests.Integration.csproj