language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore src

script:
 - dotnet build src
 - dotnet test src/Espn.Fantasy.Football.Tests.Integration.NetCore20/Espn.Fantasy.Football.Tests.Integration.NetCore20.csproj